package buildin

import (
	"bytes"
	"errors"
	"fmt"
	"github.com/Lemonn/AstUtils"
	"github.com/Lemonn/JSON2Go/internal/utils"
	"github.com/Lemonn/JSON2Go/pkg/codeGenerators"
	j2gErrors "github.com/Lemonn/JSON2Go/pkg/errors"
	"github.com/Lemonn/JSON2Go/pkg/fieldData"
	"github.com/Lemonn/JSON2Go/pkg/jsonMarshallerGenerators/marshaller"
	"github.com/Lemonn/JSON2Go/pkg/jsonMarshallerGenerators/unmarshaller"
	"github.com/Lemonn/JSON2Go/pkg/typeAdjustment"
	"github.com/dave/dst"
	"github.com/dave/dst/decorator"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"golang.org/x/mod/modfile"
	"golang.org/x/mod/module"
	"golang.org/x/mod/semver"
	"os"
	"strings"
	"time"
)

// TODO watch https://github.com/golang/go/issues/20744 and switch back to pure ast as soon as comments work!

type DstFileData struct {
	file        *dst.File
	importsFile *ast.File
	fSet        *token.FileSet
}

type DstGenerator struct {
	fileData          fieldData.FileData
	files             map[string]*DstFileData
	stackedMarshaller map[string]*dst.File
	basePath          *string
	moduleName        *string
	typeAdjuster      *typeAdjustment.TypeAdjuster
	outputPath        string
	*codeGenerators.Common
	startTime         time.Time
	globalFile        *dst.File
	globalImportsFile *ast.File
	globalFileFSet    *token.FileSet
	globalImportPath  string
	goVersion         *string
	seenFilesCount    int
	globalFileName    string
	version           string
	name              string
}

func (s *DstGenerator) GetName() string {
	return s.name
}

func (s *DstGenerator) GetVersion() string {
	return s.version
}

func (s *DstGenerator) SetActiveTypeFile(fileData fieldData.FileData) {
	s.fileData = fileData
	s.Common.SetActiveTypeFile(fileData)
	s.typeAdjuster.SetActiveTypeFile(fileData)
}

func pathBuilder(moduleName *string, basePath *string) (string, error) {
	if moduleName != nil && basePath != nil {
		return "", errors.New("cannot use both moduleName and basePath")
	} else if moduleName != nil {
		return *moduleName, nil
	} else if basePath != nil {
		return *basePath, nil
	} else {
		return "", errors.New("either packageName or basePath must be specified")
	}
}

func NewDstCodeGenerator(fileData fieldData.FileData, outputPath string, clearPath bool, moduleName *string, basePath *string, adjuster typeAdjustment.TypeDeterminationFunctions) (*DstGenerator, error) {
	internalBasePath, err := pathBuilder(moduleName, basePath)
	if err != nil {
		return nil, err
	}

	s := &DstGenerator{
		fileData:          fileData,
		files:             make(map[string]*DstFileData),
		stackedMarshaller: map[string]*dst.File{},
		basePath:          &internalBasePath,
		moduleName:        moduleName,
		outputPath:        outputPath,
		Common:            codeGenerators.NewCommon(fileData),
		startTime:         time.Now(),
		globalFile:        nil,
		globalImportsFile: nil,
		globalFileFSet:    nil,
		globalImportPath:  internalBasePath + "/Globals",
		goVersion:         utils.StringToPointer("1.23"),
		seenFilesCount:    0,
		globalFileName:    "Globals",
		version:           "",
		name:              "",
	}

	s.typeAdjuster = typeAdjustment.NewTypeAdjuster(fileData, s, adjuster, s.startTime)
	return s, nil
}

func (s *DstGenerator) addFileHeader(path string) {
	file := s.files[path].file
	file.Decs.Start.Append("// Code generated by JSON2GO. DO NOT EDIT.")
	file.Decs.Start.Append("// Version: v0.0.1")
	file.Decs.Start.Append("// CreationTime: " + s.startTime.String())
	file.Decs.Start.Append("//")
	h := s.typeAdjuster.GetFileHeader()
	for _, line := range h {
		file.Decs.Start.Append(line)
	}
}

func (s *DstGenerator) addPathFilesIfNotExists(path string) error {
	var file *dst.File
	var err error
	if _, ok := s.files[path]; !ok {
		fset := token.NewFileSet()
		pathElements := strings.Split(path, ".")
		file, err = decorator.ParseFile(fset, "", "package "+pathElements[len(pathElements)-1], parser.ParseComments)
		if err != nil {
			return err
		}

		importsFile, err := AstUtils.GetEmptyFile("imports")
		if err != nil {
			return err
		}
		s.files[path] = &DstFileData{
			file:        file,
			fSet:        fset,
			importsFile: importsFile,
		}
		s.addFileHeader(path)
	}
	return nil
}

func (s *DstGenerator) Generate() error {

	startPath, err := s.getStartPath()
	if err != nil {
		return err
	}
	pathsToProcess := []string{startPath}

	for {
		if len(pathsToProcess) == 0 {
			break
		}
		path := pathsToProcess[0]

		err := s.addPathFilesIfNotExists(path)
		if err != nil {
			return err
		}
		file := s.files[path].file
		if s.IsStruct(path) {
			var fields []*dst.Field
			var levelOfArrays int
			for levelOfArrays, _ = range s.fileData[path].Types["field"] {
				break
			}

			/// TODO replace whit a function on the adjusterLogic, that accepts a path for type adjustment

			for fieldPath, _ := range s.fileData[path].Types["field"][levelOfArrays] {
				//Adjust Types
				err := s.typeAdjuster.AdjustTypes(fieldPath)
				if err != nil {
					return err
				}
				s.stackedMarshaller[path] = file

				expr, err := s.GetAdjustedFieldType(fieldPath)
				if err != nil {
					return err
				}
				if s.IsStruct(fieldPath) {
					pathsToProcess = append(pathsToProcess, fieldPath)
					AstUtils.AddMissingImports(s.files[path].importsFile, []string{*s.basePath + strings.ReplaceAll("/"+fieldPath, ".", "/")})
				}

				pathElements := strings.Split(fieldPath, ".")
				decorate, err := decorator.Decorate(nil, expr)
				if err != nil {
					return err
				}
				field := &dst.Field{
					Names: []*dst.Ident{{Name: pathElements[len(pathElements)-1]}},
					Type:  decorate.(dst.Expr),
					Decs: dst.FieldDecorations{
						NodeDecs: dst.NodeDecs{
							Before: dst.NewLine,
							Start:  []string{"//" + fieldPath},
						},
					},
					Tag: &dst.BasicLit{Kind: token.STRING, Value: s.GetJsonTag(fieldPath)},
				}
				fields = append(fields, field)
			}
			pathElements := strings.Split(path, ".")
			file.Decls = append(file.Decls, &dst.GenDecl{
				Tok: token.TYPE,
				Specs: []dst.Spec{
					&dst.TypeSpec{
						Name: &dst.Ident{
							Name: pathElements[len(pathElements)-1],
						},
						Type: func() dst.Expr {
							return &dst.StructType{
								Fields: &dst.FieldList{List: fields},
							}
						}(),
					},
				},
			})
		} else {
			decorate, err := decorator.Decorate(nil, s.GetFieldType(path, false))
			if err != nil {
				return err
			}
			file.Decls = append(file.Decls, &dst.GenDecl{
				Tok: token.TYPE,
				Specs: []dst.Spec{
					&dst.TypeSpec{
						Name: &dst.Ident{
							Name: path,
						},
						Type: decorate.(dst.Expr),
					},
				},
			})
		}
		pathsToProcess = pathsToProcess[1:]
	}

	err = s.addJSONMarshaller()
	if err != nil {
		return err
	}

	err = s.writeFiles()
	if err != nil {
		return err
	}
	return nil
}

func (s *DstGenerator) addJSONMarshaller() error {
	var marshallGlobals, unMarshallGlobals bool
	var err error
	for path, _ := range s.stackedMarshaller {
		file := s.files[path].file
		//fSet := s.files[path].fSet
		uGen := unmarshaller.NewGenerator(s, s.fileData, s.globalImportPath)
		uDecls, imports, err := uGen.Generate(path)
		if err != nil {
			return err
		}
		if len(uDecls) > 0 {
			unMarshallGlobals = true
			for _, decl := range uDecls {
				decorate, err := decorator.Decorate(nil, decl)
				if err != nil {
					return err
				}
				file.Decls = append(file.Decls, dst.Clone(decorate).(dst.Decl))
			}

			AstUtils.AddMissingImports(s.files[path].importsFile, imports)
		}

		mGen := marshaller.NewGenerator(s.fileData, s)
		mDecl, _, err := mGen.Generate(path)
		if err != nil {
			return err
		}
		//fSet = s.files[path].fSet
		file = s.files[path].file
		if len(mDecl) > 0 {
			marshallGlobals = true
			for _, decl := range mDecl {
				decorate, err := decorator.Decorate(nil, decl)
				if err != nil {
					return err
				}
				file.Decls = append(file.Decls, dst.Clone(decorate).(dst.Decl))
			}
			AstUtils.AddMissingImports(s.files[path].importsFile, imports)
		}

		err = s.addTypeConverterFunctions(path, file)
		if err != nil {
			return err
		}

	}

	if s.globalFile == nil {
		fset := token.NewFileSet()
		s.globalFileFSet = fset
		s.globalFile, err = decorator.ParseFile(fset, "", "package Globals", parser.ParseComments)
		if err != nil {
			return err
		}

		s.globalImportsFile, err = parser.ParseFile(token.NewFileSet(), "", "package Globals", parser.ParseComments)
		if err != nil {
			return err
		}
	}

	if unMarshallGlobals {
		uGen := unmarshaller.NewGenerator(s, s.fileData, s.globalImportPath)
		uGGen, uGImports := uGen.GetGlobalFunctions()

		for _, decl := range uGGen {
			decorate, err := decorator.Decorate(nil, decl)
			if err != nil {
				return err
			}
			s.globalFile.Decls = append(s.globalFile.Decls, decorate.(dst.Decl))
		}

		AstUtils.AddMissingImports(s.globalImportsFile, uGImports)
	}

	if marshallGlobals {
		mGen := marshaller.NewGenerator(s.fileData, s)
		mGGen := mGen.GetGlobalFunctions()
		for _, decl := range mGGen {
			decorate, err := decorator.Decorate(nil, decl)
			if err != nil {
				return err
			}
			s.globalFile.Decls = append(s.globalFile.Decls, decorate.(dst.Decl))
		}
	}

	if s.moduleName != nil {
		mod, err := s.generateGoMod()
		if err != nil {
			return err
		}
		err = os.WriteFile(s.outputPath+"/go.mod", mod, 0666)
		if err != nil {
			return err
		}
	}
	return nil
}

func (s *DstGenerator) generateGoMod() ([]byte, error) {
	file, err := modfile.Parse("", []byte("module "+*s.moduleName+"\n\ngo "+*s.goVersion+"\n\n"), nil)
	if err != nil {
		return nil, err
	}

	var requiresMap map[string]*fieldData.ModFileContent
	for _, pathData := range s.fileData {
		if pathData.TypeAdjusterData != nil && pathData.TypeAdjusterData.ModFileContents != nil {
			for _, modFileContent := range pathData.TypeAdjusterData.ModFileContents {
				if !semver.IsValid(modFileContent.Version) {
					return nil, fmt.Errorf("invalid semver version: %s", modFileContent.Version)
				}
				if v, ok := requiresMap[modFileContent.Path]; !ok {
					requiresMap[modFileContent.Path] = modFileContent
				} else {
					if semver.Compare(v.Version, modFileContent.Version) == -1 {
						requiresMap[modFileContent.Path].Version = modFileContent.Version
					}
					if !requiresMap[modFileContent.Path].Indirect || !modFileContent.Indirect {
						requiresMap[modFileContent.Path].Indirect = false
					}
				}
			}
		}
	}
	var requires []*modfile.Require
	for _, content := range requiresMap {
		requires = append(requires, &modfile.Require{
			Mod: module.Version{
				Path:    content.Path,
				Version: content.Version,
			},
			Indirect: content.Indirect,
		})
	}
	file.SetRequireSeparateIndirect(requires)
	return file.Format()
}

func (s *DstGenerator) addTypeConverterFunctions(path string, file *dst.File) error {
	var elements map[string]*fieldData.ValueDetails
	for level, _ := range s.fileData[path].Types[s.GetType(path)] {
		elements = s.fileData[path].Types[s.GetType(path)][level]
	}

	for elementPath, _ := range elements {
		if s.fileData[elementPath].TypeAdjusterData != nil && s.fileData[elementPath].TypeAdjusterData.ParseFunctions != nil {
			AstUtils.AddMissingImports(s.files[path].importsFile, s.fileData[elementPath].TypeAdjusterData.ParseFunctions.MarshallImports)
			MarshallExprFile, err := decorator.ParseFile(token.NewFileSet(), "", "package main \n"+s.fileData[elementPath].TypeAdjusterData.ParseFunctions.Marshall, parser.AllErrors)
			if err != nil {
				return err
			}
			file.Decls = append(file.Decls, MarshallExprFile.Decls[0])

			AstUtils.AddMissingImports(s.files[path].importsFile, s.fileData[elementPath].TypeAdjusterData.ParseFunctions.UnmarshallImports)
			UnMarshallExprFile, err := decorator.ParseFile(token.NewFileSet(), "", "package main \n"+s.fileData[elementPath].TypeAdjusterData.ParseFunctions.Unmarshall, parser.AllErrors)
			if err != nil {
				return err
			}
			file.Decls = append(file.Decls, UnMarshallExprFile.Decls[0])
		}
	}
	return nil
}

func (s *DstGenerator) getStartPath() (string, error) {
	for path, _ := range s.fileData {
		pathElements := strings.Split(path, ".")
		if len(pathElements) == 1 {
			return pathElements[0], nil
		}
	}
	return "", errors.New("start path not found")
}

func (s *DstGenerator) writeFiles() error {
	for path, file := range s.files {
		if len(file.importsFile.Decls) > 0 {
			imports, err := decorator.Decorate(nil, file.importsFile.Decls[0])
			if err != nil {
				return err
			}
			file.file.Decls = append([]dst.Decl{imports.(dst.Decl)}, file.file.Decls...)
		}

		err := os.MkdirAll(strings.ReplaceAll(s.outputPath+"/"+path, ".", "/"), os.ModePerm)
		if err != nil {
			return err
		}
		output := bytes.NewBuffer([]byte{})
		if err := decorator.Fprint(output, file.file); err != nil {
			return err
		}
		c, err := format.Source(output.Bytes())
		if err != nil {
			return err
		}
		pathElements := strings.Split(path, ".")
		err = os.WriteFile(strings.ReplaceAll(s.outputPath+"/"+path, ".", "/")+"/"+pathElements[len(pathElements)-1]+".go", c, 0666)
		if err != nil {
			return err
		}
	}

	if s.globalFile != nil {
		output := bytes.NewBuffer([]byte{})

		if len(s.globalImportsFile.Decls) > 0 {
			imports, err := decorator.Decorate(nil, s.globalImportsFile.Decls[0])
			if err != nil {
				return err
			}
			s.globalFile.Decls = append([]dst.Decl{imports.(dst.Decl)}, s.globalFile.Decls...)
		}

		if err := decorator.Fprint(output, s.globalFile); err != nil {
			return err
		}
		c, err := format.Source(output.Bytes())
		if err != nil {
			return err
		}
		err = os.MkdirAll(s.outputPath+"/Globals", os.ModePerm)
		if err != nil {
			return err
		}
		err = os.WriteFile(s.outputPath+"/Globals/globals.go", c, 0666)
		if err != nil {
			return err
		}
	}

	return nil
}

func (s *DstGenerator) CheckType(path string) error {
	pathData := s.fileData[path]
	if pathData.TypeAdjusterData != nil && pathData.TypeAdjusterData.NameOfActiveTypeAdjuster != nil {
		return s.typeAdjuster.CheckActiveChecker(path, true)
	} else if pathData.ActiveType != nil {
		typeString, err := utils.ExprToString(s.GetFieldType(path, true))
		if err != nil {
			return err
		}
		if *pathData.ActiveType != typeString {
			return &j2gErrors.TypeChangeError{
				OldType: *pathData.ActiveType,
				NewType: typeString,
			}
		}
	}
	return nil
}
