package fieldData

import (
	"encoding/json"
	"errors"
	"fmt"
	"reflect"
)

type Metadata struct {
	TotalSampleCount int                          `json:"totalSampleCount"`
	LastRunTimestamp int64                        `json:"lastRunTimestamp"`
	Data             map[string]*TypeAdjusterData `json:"data"`
}

type TypeAdjusterData struct {
	// NameOfActiveTypeAdjuster Name of the TypeAdjuster that replaced the type
	NameOfActiveTypeAdjuster *string `json:"nameOfActiveTypeAdjuster,omitempty"`
	// TypeAdjusterData Data stored by the currently in used TypeAdjuster. This is used to emmit the
	// IncompatibleCustomType error, for example if a type such as time.Time stays the same but the underling
	// time strings are incompatible
	TypeAdjusterData []*json.RawMessage `json:"typeAdjusterData,omitempty"`
	// ExcludedTypeCheckers List of TypeChecker names that should not be run on this field.
	ExcludedTypeCheckers []string `json:"excludedTypeCheckers,omitempty"`
	// CheckedNonMatchingTypes Is used to store a map of non-matching types referencing the time of storage as unix timestamp.
	// This is useful when working with a lot of input data, and the seen values becomes to big
	CheckedNonMatchingTypes map[string]int64 `json:"checkedNonMatchingTypes,omitempty"`
	// ParseFunctions Holds the names of the parse functions generated by TypeDeterminationFunction
	ParseFunctions *ParseFunctions `json:"parseFunctions,omitempty"`
	// BaseType The type before it was modified from a TypeDeterminationFunction
	BaseType *string `json:"baseType,omitempty"`
}

type PathData struct {
	Types map[Type]map[int]map[string]*ValueDetails `json:"types,omitempty"`
	// Contains the name, as found in the JSON-File
	JsonFieldName    string            `json:"jsonFieldName,omitempty"`
	Package          *string           `json:"package,omitempty"`
	Omitempty        bool              `json:"omitempty,omitempty"`
	TypeAdjusterData *TypeAdjusterData `json:"typeAdjusterData,omitempty"`
	// Error Holds an error of type FieldPresenceChangeError, errors.IncompatibleCustomTypeError or errors.TypeChangeError.
	// It's up to the caller, what to do with this. errors.IncompatibleCustomTypeError or TypeChangeError
	// indicate a major version change. Should be set to nil, before next run!
	Error error `json:"error,omitempty"`
	// RequiredField set to true, if the unmarshall generator should make this a required field.
	RequiredField bool `json:"requiredField,omitempty"`
}

func (p *PathData) Combine(p1 *PathData) (*PathData, error) {
	newP := PathData{Types: make(map[Type]map[int]map[string]*ValueDetails)}
	for t, arrayLevels := range p.Types {
		if _, ok := newP.Types[t]; !ok {
			newP.Types[t] = make(map[int]map[string]*ValueDetails)
		}
		for level, valueDetails := range arrayLevels {
			if _, ok := newP.Types[t][level]; !ok {
				newP.Types[t][level] = map[string]*ValueDetails{}
			}
			for value, valueDetail := range valueDetails {
				if _, ok := newP.Types[t][level][value]; !ok {
					newP.Types[t][level][value] = valueDetail
				} else {
					newP.Types[t][level][value].Combine(valueDetail)
				}
			}

		}
	}
	for t, arrayLevels := range p1.Types {
		if _, ok := newP.Types[t]; !ok {
			newP.Types[t] = make(map[int]map[string]*ValueDetails)
		}
		for level, valueDetails := range arrayLevels {
			if _, ok := newP.Types[t][level]; !ok {
				newP.Types[t][level] = map[string]*ValueDetails{}
			}
			for value, valueDetail := range valueDetails {
				if _, ok := newP.Types[t][level][value]; !ok {
					newP.Types[t][level][value] = valueDetail
				} else {
					newP.Types[t][level][value].Combine(valueDetail)
				}
			}

		}
	}
	//TODO combine simple fields
	return &newP, nil
}

type ValueDetails struct {
	Count              int
	FirstSeenTimestamp int64
	LastSeenTimestamp  int64
}

func (v *ValueDetails) Combine(v1 *ValueDetails) *ValueDetails {
	var combinedValueDetails ValueDetails
	//Combine Count
	combinedValueDetails.Count = v.Count + v1.Count
	//Combine FirstSeenTimestamp
	if v.FirstSeenTimestamp < v1.FirstSeenTimestamp {
		combinedValueDetails.FirstSeenTimestamp = v.FirstSeenTimestamp
	} else {
		combinedValueDetails.FirstSeenTimestamp = v1.FirstSeenTimestamp
	}
	// Combine LastSeenTimestamp
	if v.LastSeenTimestamp > v1.LastSeenTimestamp {
		combinedValueDetails.LastSeenTimestamp = v.LastSeenTimestamp
	} else {
		combinedValueDetails.LastSeenTimestamp = v1.LastSeenTimestamp
	}
	return &combinedValueDetails
}

// ParseFunctions Holds the names of the parse functions
type ParseFunctions struct {
	// FromTypeParseFunction Holds the function name, which converts from json to custom type
	FromTypeParseFunction string `json:"fromTypeParseFunction,omitempty"`
	// ToTypeParseFunction Holds the function name, which converts from custom to json type
	ToTypeParseFunction string `json:"toTypeParseFunction,omitempty"`
}

type Type string

const (
	String      Type = "string"
	Float64     Type = "float64"
	Bool        Type = "bool"
	Field       Type = "field"
	Unsupported Type = "unsupported"
)

func TypeFromAny(a any) (Type, error) {
	return NewType(reflect.TypeOf(a).String())
}

func NewType(s string) (Type, error) {
	switch s {
	case "string":
		return String, nil
	case "float64":
		return Float64, nil
	case "bool":
		return Bool, nil
	case "field":
		return Field, nil
	default:
		return Unsupported, errors.New(fmt.Sprintf("encountred an unsupported type: %s", s))
	}
}
