package fieldData

import "encoding/json"

type TypeAdjusterData struct {
	// NameOfActiveTypeAdjuster Name of the TypeAdjuster that replaced the type
	NameOfActiveTypeAdjuster *string `json:"nameOfActiveTypeAdjuster,omitempty"`
	// TypeAdjusterData Data stored by the currently in used TypeAdjuster. This is used to emmit the
	// IncompatibleCustomType error, for example if a type such as time.Time stays the same but the underling
	// time strings are incompatible
	TypeAdjusterData []json.RawMessage `json:"typeAdjusterData,omitempty"`
	// ExcludedTypeCheckers List of TypeChecker names that should not be run on this field.
	ExcludedTypeCheckers []string `json:"excludedTypeCheckers,omitempty"`
	// CheckedNonMatchingTypes Is used to store a map of non-matching types referencing the time of storage as unix timestamp.
	// This is useful when working with a lot of input data, and the seen values becomes to big
	CheckedNonMatchingTypes map[string]int64 `json:"checkedNonMatchingTypes,omitempty"`
	// ParseFunctions Holds the names of the parse functions generated by TypeDeterminationFunction
	ParseFunctions *ParseFunctions `json:"parseFunctions,omitempty"`
	// SetTimestamp Timestamp when the type replacement became active
	SetTimestamp         int64             `json:"setTimestamp"`
	LastCheckedTimestamp int64             `json:"lastCheckedTimestamp"`
	CheckerVersion       string            `json:"checkerVersion,omitempty"`
	ModFileContents      []*ModFileContent `json:"modFileContents,omitempty"`
}

func (t *TypeAdjusterData) Combine(t1 *TypeAdjusterData) (*TypeAdjusterData, error) {
	//TODO implement
	return t, nil
}

// ParseFunctions Holds the names of the parse functions
type ParseFunctions struct {
	// FromTypeParseFunction Holds the function code of the
	Unmarshall        string   `json:"unmarshall,omitempty"`
	UnmarshallImports []string `json:"unmarshallImports,omitempty"`
	// ToTypeParseFunction Holds the function name, which converts from custom to json type
	Marshall        string   `json:"marshall,omitempty"`
	MarshallImports []string `json:"marshallImports,omitempty"`
}

type ModFileContent struct {
	Path     string `json:"path"`
	Version  string `json:"version"`
	Indirect bool   `json:"indirect"`
}
