package fieldData

import (
	"encoding/json"
	"errors"
	j2gErrors "github.com/Lemonn/JSON2Go/pkg/errors"
)

type TypeAdjusterData struct {
	// NameOfActiveTypeAdjuster Name of the TypeAdjuster that replaced the type
	NameOfActiveTypeAdjuster *string `json:"nameOfActiveTypeAdjuster,omitempty"`
	// TypeAdjusterData Data stored by the currently in used TypeAdjuster. This is used to emmit the
	// IncompatibleCustomType error, for example if a type such as time.Time stays the same but the underling
	// time strings are incompatible
	TypeAdjusterData []json.RawMessage `json:"typeAdjusterData,omitempty"`
	// ExcludedTypeCheckers List of TypeChecker names that should not be run on this field.
	ExcludedTypeCheckers []string `json:"excludedTypeCheckers,omitempty"`
	// CheckedNonMatchingTypes Is used to store a map of non-matching types referencing the time of storage as unix timestamp.
	// This is useful when working with a lot of input data, and the seen values becomes to big
	// TODO include the checker version, use an struct to do so
	CheckedNonMatchingTypes map[string]int64 `json:"checkedNonMatchingTypes,omitempty"`
	// ParseFunctions Holds the names of the parse functions generated by TypeDeterminationFunction
	ParseFunctions *ParseFunctions `json:"parseFunctions,omitempty"`
	// SetTimestamp Timestamp when the type replacement became active
	SetTimestamp         *int64            `json:"setTimestamp,omitempty"`
	LastCheckedTimestamp *int64            `json:"lastCheckedTimestamp,omitempty"`
	CheckerVersion       *string           `json:"checkerVersion,omitempty"`
	ModFileContents      []*ModFileContent `json:"modFileContents,omitempty"`
}

func (t *TypeAdjusterData) Combine(t1 *TypeAdjusterData) (*TypeAdjusterData, error) {
	if t1 == nil {
		return t, nil
	}

	//Combine NameOfActiveTypeAdjuster
	var tNew TypeAdjusterData
	var err error
	if t1.NameOfActiveTypeAdjuster == nil {
		tNew.NameOfActiveTypeAdjuster = t.NameOfActiveTypeAdjuster
	} else if t.NameOfActiveTypeAdjuster == nil {
		tNew.NameOfActiveTypeAdjuster = t1.NameOfActiveTypeAdjuster
	} else if *t.NameOfActiveTypeAdjuster != *t1.NameOfActiveTypeAdjuster {
		err = errors.Join(err, &j2gErrors.ConflictingCustomTypesError{
			OldTypeAdjuster: *t.NameOfActiveTypeAdjuster,
			NewTypeAdjuster: *t1.NameOfActiveTypeAdjuster,
		})
	}

	tNew.TypeAdjusterData = []json.RawMessage{}
	tNew.TypeAdjusterData = append(tNew.TypeAdjusterData, t.TypeAdjusterData...)
	tNew.TypeAdjusterData = append(tNew.TypeAdjusterData, t1.TypeAdjusterData...)

	//Combine excludedTypeCheckers
	excludedTypeCheckers := make(map[string]struct{})
	for _, checkerName := range t.ExcludedTypeCheckers {
		excludedTypeCheckers[checkerName] = struct{}{}
	}
	for _, checkerName := range t1.ExcludedTypeCheckers {
		excludedTypeCheckers[checkerName] = struct{}{}
	}
	tNew.ExcludedTypeCheckers = []string{}
	for checkerName, _ := range excludedTypeCheckers {
		tNew.ExcludedTypeCheckers = append(tNew.ExcludedTypeCheckers, checkerName)
	}

	//Combine CheckedNonMatchingTypes
	tNew.CheckedNonMatchingTypes = make(map[string]int64)
	for checkerName, timestamp := range t.CheckedNonMatchingTypes {
		if ts, ok := tNew.CheckedNonMatchingTypes[checkerName]; (ok && ts < timestamp) || !ok {
			tNew.CheckedNonMatchingTypes[checkerName] = timestamp
		}
	}
	for checkerName, timestamp := range t1.CheckedNonMatchingTypes {
		if ts, ok := tNew.CheckedNonMatchingTypes[checkerName]; (ok && ts < timestamp) || !ok {
			tNew.CheckedNonMatchingTypes[checkerName] = timestamp
		}
	}
	return &tNew, err
}

// ParseFunctions Holds the names of the parse functions
type ParseFunctions struct {
	// FromTypeParseFunction Holds the function code of the
	Unmarshall        string   `json:"unmarshall,omitempty"`
	UnmarshallImports []string `json:"unmarshallImports,omitempty"`
	// ToTypeParseFunction Holds the function name, which converts from custom to json type
	Marshall        string   `json:"marshall,omitempty"`
	MarshallImports []string `json:"marshallImports,omitempty"`
}

type ModFileContent struct {
	Path     string `json:"path"`
	Version  string `json:"version"`
	Indirect bool   `json:"indirect"`
}
