package fieldData

import (
	"encoding/json"
	"errors"
	j2gErrors "github.com/Lemonn/JSON2Go/pkg/errors/combiner"
)

type TypeAdjusterData struct {
	// NameOfActiveTypeAdjuster Name of the TypeAdjuster that replaced the type
	NameOfActiveTypeAdjuster *string `json:"nameOfActiveTypeAdjuster,omitempty"`
	// TypeAdjusterData Data stored by the currently in used TypeAdjuster. This is used to emmit the
	// IncompatibleCustomType error, for example if a type such as time.Time stays the same but the underling
	// time strings are incompatible
	TypeAdjusterData []json.RawMessage `json:"typeAdjusterData,omitempty"`
	// ExcludedTypeCheckers List of TypeChecker names that should not be run on this field.
	ExcludedTypeCheckers []string `json:"excludedTypeCheckers,omitempty"`
	// CheckedNonMatchingTypes Is used to store a map of non-matching types referencing the time of storage as unix timestamp.
	// This is useful when working with a lot of input data, and the seen values becomes to big
	CheckedNonMatchingTypes map[string]*NonMatchingCheckerInfos `json:"checkedNonMatchingTypes,omitempty"`
	// ParseFunctions Holds the names of the parse functions generated by TypeDeterminationFunction
	//ParseFunctions *ParseFunctions `json:"parseFunctions,omitempty"`
	// SetTimestamp Timestamp when the type replacement became active
	SetTimestamp *int64 `json:"setTimestamp,omitempty"`
	// LastCheckedTimestamp Updated whenever the checker is run
	LastCheckedTimestamp *int64 `json:"lastCheckedTimestamp,omitempty"`
	// CheckerVersion Contains the version of the checker
	CheckerVersion *string `json:"checkerVersion,omitempty"`
	// ModFileContents Sets imports for the go.mod, if an import is a duplicate, the newer version wins -> do not use
	// this here, use the checker version to decide if a new generation is necessary
	//ModFileContents []*ModFileContent `json:"modFileContents,omitempty"`
	// Prefix used to prevent name conflict when generating nested types
	Prefix              *string `json:"prefix,omitempty"`
	DoNotUseCustomTypes bool    `json:"doNotUseCustomTypes,omitempty"`
}

type NonMatchingCheckerInfos struct {
	Timestamp int64   `json:"timestamp,omitempty"`
	Version   *string `json:"version,omitempty"`
}

func (n *NonMatchingCheckerInfos) combine(n1 *NonMatchingCheckerInfos) *NonMatchingCheckerInfos {
	var NewN NonMatchingCheckerInfos
	if n == nil && n1 == nil {
		return nil
	} else if n == nil {
		NewN.Timestamp = n1.Timestamp
		NewN.Version = n1.Version
	} else if n1 == nil {
		NewN.Timestamp = n.Timestamp
		NewN.Version = n.Version
	} else if n.Timestamp > n1.Timestamp {
		NewN.Timestamp = n.Timestamp
		NewN.Version = n.Version
	} else {
		NewN.Timestamp = n1.Timestamp
		NewN.Version = n1.Version
	}
	return &NewN
}

func (t *TypeAdjusterData) Combine(t1 *TypeAdjusterData) (*TypeAdjusterData, error) {
	if t1 == nil {
		return t, nil
	}

	//Combine NameOfActiveTypeAdjuster
	var tNew TypeAdjusterData
	var err error
	if t1.NameOfActiveTypeAdjuster == nil {
		tNew.NameOfActiveTypeAdjuster = t.NameOfActiveTypeAdjuster
	} else if t.NameOfActiveTypeAdjuster == nil {
		tNew.NameOfActiveTypeAdjuster = t1.NameOfActiveTypeAdjuster
	} else if *t.NameOfActiveTypeAdjuster != *t1.NameOfActiveTypeAdjuster {
		err = errors.Join(err, &j2gErrors.ConflictingCustomTypesError{
			OldTypeAdjuster: *t.NameOfActiveTypeAdjuster,
			NewTypeAdjuster: *t1.NameOfActiveTypeAdjuster,
		})
	}

	tNew.TypeAdjusterData = []json.RawMessage{}
	tNew.TypeAdjusterData = append(tNew.TypeAdjusterData, t.TypeAdjusterData...)
	tNew.TypeAdjusterData = append(tNew.TypeAdjusterData, t1.TypeAdjusterData...)

	//Combine excludedTypeCheckers
	excludedTypeCheckers := make(map[string]struct{})
	for _, checkerName := range t.ExcludedTypeCheckers {
		excludedTypeCheckers[checkerName] = struct{}{}
	}
	for _, checkerName := range t1.ExcludedTypeCheckers {
		excludedTypeCheckers[checkerName] = struct{}{}
	}
	tNew.ExcludedTypeCheckers = []string{}
	for checkerName, _ := range excludedTypeCheckers {
		tNew.ExcludedTypeCheckers = append(tNew.ExcludedTypeCheckers, checkerName)
	}

	//Combine CheckedNonMatchingTypes
	tNew.CheckedNonMatchingTypes = make(map[string]*NonMatchingCheckerInfos)
	for checkerName, infos := range t.CheckedNonMatchingTypes {
		if ts, ok := tNew.CheckedNonMatchingTypes[checkerName]; !ok {
			tNew.CheckedNonMatchingTypes[checkerName] = infos
		} else {
			tNew.CheckedNonMatchingTypes[checkerName] = ts.combine(infos)
		}
	}
	for checkerName, infos := range t1.CheckedNonMatchingTypes {
		if ts, ok := tNew.CheckedNonMatchingTypes[checkerName]; !ok {
			tNew.CheckedNonMatchingTypes[checkerName] = infos
		} else {
			tNew.CheckedNonMatchingTypes[checkerName] = ts.combine(infos)
		}
	}
	return &tNew, err
}

/*
// ParseFunctions Holds the names of the parse functions
type ParseFunctions struct {
	// FromTypeParseFunction Holds the function code of the
	Unmarshall        string   `json:"unmarshall,omitempty"`
	UnmarshallImports []string `json:"unmarshallImports,omitempty"`
	// ToTypeParseFunction Holds the function name, which converts from custom to json type
	Marshall        string           `json:"marshall,omitempty"`
	MarshallImports []string         `json:"marshallImports,omitempty"`
	File            map[string]*File `json:"subFiles,omitempty"`
}

*/
